DEBUG 2023-03-23 11:15:08.602 UTC: 	 CRAB Client version: v3.230124
DEBUG 2023-03-23 11:15:08.602 UTC: 	 Running on: Linux lxplus787.cern.ch 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-03-23 11:15:08.602 UTC: 	 Executing command: 'submit'
DEBUG 2023-03-23 11:15:08.602 UTC: 	 Could not find CRAB cache file /afs/cern.ch/user/a/almuhamm/.crab3; creating a new one.
INFO 2023-03-23 11:15:08.608 UTC: 	 Will use CRAB configuration file ZMu_Crab.py
DEBUG 2023-03-23 11:15:08.608 UTC: 	 Loading CRAB configuration file.
ERROR 2023-03-23 11:15:08.640 UTC: 	 Invalid CRAB configuration: Parameter JobType.pluginName has an invalid value ('OmtfAnalysis').
Allowed values are: ANALYSIS, PRIVATEMC, COPYCAT.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2023-03-23 11:15:08.640 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/SubCommand.py", line 94, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Invalid CRAB configuration: Parameter JobType.pluginName has an invalid value ('OmtfAnalysis').
Allowed values are: ANALYSIS, PRIVATEMC, COPYCAT.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2023-03-23 11:15:08.647 UTC: 	 Log file is /eos/home-a/almuhamm/01.MuonTech/CMSSW_12_6_3/src/UserCode/OmtfAnalysis/test/crab.log
DEBUG 2023-03-23 16:17:03.824 UTC: 	 CRAB Client version: v3.230124
DEBUG 2023-03-23 16:17:03.824 UTC: 	 Running on: Linux lxplus787.cern.ch 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-03-23 16:17:03.824 UTC: 	 Executing command: 'submit'
DEBUG 2023-03-23 16:17:03.825 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/almuhamm/.crab3
INFO 2023-03-23 16:17:03.854 UTC: 	 Will use CRAB configuration file ZMu_Crab.py
DEBUG 2023-03-23 16:17:03.855 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-03-23 16:17:03.912 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-03-23 16:17:03.916 UTC: 	 Working area '/eos/home-a/almuhamm/01.MuonTech/CMSSW_12_6_3/src/UserCode/OmtfAnalysis/test/OMTF_Inhouse/crab_L1T_Eff' already exists 
Please change the requestName in the config file
ERROR 2023-03-23 16:17:03.916 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/SubCommand.py", line 318, in __init__
    self.requestarea, self.requestname, self.logfile = createWorkArea(
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/ClientUtilities.py", line 387, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
CRABClient.ClientExceptions.ConfigException: Working area '/eos/home-a/almuhamm/01.MuonTech/CMSSW_12_6_3/src/UserCode/OmtfAnalysis/test/OMTF_Inhouse/crab_L1T_Eff' already exists 
Please change the requestName in the config file
INFO 2023-03-23 16:17:03.920 UTC: 	 Log file is /eos/home-a/almuhamm/01.MuonTech/CMSSW_12_6_3/src/UserCode/OmtfAnalysis/test/crab.log
DEBUG 2023-03-24 14:01:52.392 UTC: 	 CRAB Client version: v3.230124
DEBUG 2023-03-24 14:01:52.392 UTC: 	 Running on: Linux lxplus774.cern.ch 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-03-24 14:01:52.392 UTC: 	 Executing command: 'status'
DEBUG 2023-03-24 14:01:52.393 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/almuhamm/.crab3
DEBUG 2023-03-24 14:56:25.413 UTC: 	 CRAB Client version: v3.230124
DEBUG 2023-03-24 14:56:25.413 UTC: 	 Running on: Linux lxplus774.cern.ch 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-03-24 14:56:25.413 UTC: 	 Executing command: 'submit'
DEBUG 2023-03-24 14:56:25.414 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/almuhamm/.crab3
ERROR 2023-03-24 14:56:25.415 UTC: 	 CRAB configuration file crabConfig.py not found.
ERROR 2023-03-24 14:56:25.415 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/SubCommand.py", line 51, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
CRABClient.ClientExceptions.ConfigurationException: CRAB configuration file crabConfig.py not found.
INFO 2023-03-24 14:56:25.423 UTC: 	 Log file is /eos/home-a/almuhamm/01.MuonTech/CMSSW_12_6_3/src/UserCode/OmtfAnalysis/test/crab.log
DEBUG 2023-03-24 14:56:59.708 UTC: 	 CRAB Client version: v3.230124
DEBUG 2023-03-24 14:56:59.708 UTC: 	 Running on: Linux lxplus774.cern.ch 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-03-24 14:56:59.708 UTC: 	 Executing command: 'submit'
DEBUG 2023-03-24 14:56:59.708 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/almuhamm/.crab3
INFO 2023-03-24 14:56:59.709 UTC: 	 Will use CRAB configuration file ZMu_Crab.py
DEBUG 2023-03-24 14:56:59.709 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-03-24 14:56:59.763 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-03-24 14:56:59.763 UTC: 	 Task requests 8000 MB of memory, above the allowed maximum of 5000 for a 1 core(s) job.

The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2023-03-24 14:56:59.763 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/SubCommand.py", line 94, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Task requests 8000 MB of memory, above the allowed maximum of 5000 for a 1 core(s) job.

The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2023-03-24 14:56:59.770 UTC: 	 Log file is /eos/home-a/almuhamm/01.MuonTech/CMSSW_12_6_3/src/UserCode/OmtfAnalysis/test/crab.log
DEBUG 2023-03-24 14:58:55.360 UTC: 	 CRAB Client version: v3.230124
DEBUG 2023-03-24 14:58:55.361 UTC: 	 Running on: Linux lxplus774.cern.ch 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-03-24 14:58:55.361 UTC: 	 Executing command: 'submit'
DEBUG 2023-03-24 14:58:55.361 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/almuhamm/.crab3
INFO 2023-03-24 14:58:55.363 UTC: 	 Will use CRAB configuration file ZMu_Crab.py
DEBUG 2023-03-24 14:58:55.363 UTC: 	 Loading CRAB configuration file.
DEBUG 2023-03-24 14:58:55.464 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2023-03-24 14:58:55.464 UTC: 	 Task requests 8000 MB of memory, above the allowed maximum of 5000 for a 1 core(s) job.

The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2023-03-24 14:58:55.464 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/SubCommand.py", line 94, in loadConfig
    raise ConfigurationException(configmsg)
CRABClient.ClientExceptions.ConfigurationException: Task requests 8000 MB of memory, above the allowed maximum of 5000 for a 1 core(s) job.

The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2023-03-24 14:58:55.499 UTC: 	 Log file is /eos/home-a/almuhamm/01.MuonTech/CMSSW_12_6_3/src/UserCode/OmtfAnalysis/test/crab.log
